language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -s --cov-report term-missing --cov autovers -v
after_success:
  - coveralls
